### ISSUE TITLE
Table: ez NFT Sales

### ISSUE THREAD

**Issue by forgxyz** [MetricsDAO/near_dbt#91]
A NFT Sales table should parse transactions, actions, and receipts for the sale and transfer of NFTs and include the following curated data in a core `ez_` view:

- buyer
- seller
- platform
- platform contract and/or version, if available
- nft address
- nft project, if available
- nft id, if available
- price
- currency
- platform fee or royalty, if available
- network fee
- tx status

TODO:
- [ ] Explore data for available information
- [ ] Design schema
- [ ] Review schema with pod
- [ ] Build data models
- [ ] Submit for review

**Comment by geewynn** [comment]
While exploring the data, i was able map some columns on the tx table to some columns on the schema above.

buyer - receiver_id
seller - tx-signer/sender-id 
price - amount
tx status - tx_status
platform - tx_receiver
nft address - tx_receiver

Question
1. **platform - tx_receiver.** what is the platform here? is this the nft project?
**currency** - not sure about this
**network fee** - what is the network fee? is this same as the transaction fee?
**nft address** - I am assuming this is the nft contract address which is same as the tx_receiver.
**nft project**, if available - same as above
**nft id**, if available - not available
platform fee or royalty, if available - not sure about this .
platform contract and/or version, if available - not sure about this .

**Comment by forgxyz** [comment]
> **platform - tx_receiver.** what is the platform here? is this the nft project?  
Paras is a large NFT platform on NEAR, for example. Is there some contract interaction in actions or receipts that tell us this? Unsure of other NFT platforms, just an example.

>**currency** - not sure about this  
We should be able to determine from the token transfer - is it always NEAR, or do they use USN, or another token?

>**network fee** - what is the network fee? is this same as the transaction fee?  
Yes, transaction fee / gas.

>**nft project**, if available - same as above  
The name of the collection, looking at Paras for an example: https://paras.id/collection/nearnautnft.near
This would be NEARNauts. Contract name `nearnautnft.near` is ok to list here.

>**nft address** - I am assuming this is the nft contract address which is same as the tx_receiver.  
>**nft id**, if available - not available  
Unsure about `tx_receiver` but yes, the contract address for the NFT itself. Lumping these together because I am unsure how NFTs are represented on chain. Using above example, NEARNauts is a collection. Is NEARNaut 1000 represented as a token / contract address? If so, that would be added to the `nft address` column. If we can determine it is 1000, or if it has a separate on-chain ID of some sort, that is `nft id`.

>platform fee or royalty, if available - not sure about this .  
Does Paras collect a royalty? Does the collection owner? If determinable, we can include. If not, that's fine.

>platform contract and/or version, if available - not sure about this .
Has Paras, or another marketplace, gone from v1 to v2, for example, and do we need to account for any transaction structure changes?

**Comment by geewynn** [comment]
**Paras is a large NFT platform on NEAR, for example. Is there some contract interaction in actions or receipts that tell us this? Unsure of other NFT platforms, just an example.**
> Yes, the tx-receiver shows the interaction with the nft platform.
![image](https://user-images.githubusercontent.com/29405050/185473432-1e59f478-e70e-4242-90c1-ad0bf00a04aa.png)

**We should be able to determine from the token transfer - is it always NEAR, or do they use USN, or another token?**
> From what i see in the receipt logs, the currency is a little bit hard to determine, for example in the logs in the below image. I am inclined to say the currency here is the nft platform
![image](https://user-images.githubusercontent.com/29405050/185475999-a23bd078-5b1e-4002-adda-7e7b1faf68ba.png)

**nft address - I am assuming this is the nft contract address which is same as the tx_receiver.
nft id, if available - not available
Unsure about tx_receiver but yes, the contract address for the NFT itself. Lumping these together because I am unsure how NFTs are represented on chain. Using above example, NEARNauts is a collection. Is NEARNaut 1000 represented as a token / contract address? If so, that would be added to the nft address column. If we can determine it is 1000, or if it has a separate on-chain ID of some sort, that is nft id.**
> they are represented with the tokenId, this means we can go with the nftId(tokenId)
![image](https://user-images.githubusercontent.com/29405050/185477976-b9f83d73-f5f7-4696-8dae-205a8d7ace4e.png)

**The name of the collection, looking at Paras for an example: https://paras.id/collection/nearnautnft.near
This would be NEARNauts. Contract name nearnautnft.near is ok to list here.**
> I am not sure this is available in the tx data. 

**Has Paras, or another marketplace, gone from v1 to v2, for example, and do we need to account for any transaction structure changes?**
This too, looks interesting, will poke around more if i can find anything relating to the nft platform.

**Comment by forgxyz** [comment]
Ok, I think you are on the right track with the schema and the information we can pull out of the transactions @geewynn 

Also - Query that should assist with the ez table: https://app.flipsidecrypto.com/velocity/queries/b4781971-7539-41ef-9c1e-4af08afb79de
